import { useState } from "react";
import Head from "next/head";
import Personalizador from "@/components/Personalizador/Personalizador";
import SeleccionadorModelo from "@/components/SeleccionadorModelo/SeleccionadorModelo";
import SeleccionadorPalma from "@/components/SeleccionadorPalma/SeleccionadorPalma";
import SeleccionadorLatigo from "@/components/SeleccionadorLatigo/SeleccionadorLatigo";
import {
  SELECCIONAR_BASE,
  SELECCIONAR_PALMA,
  SELECCIONAR_LATIGO,
  SELECCIONAR_COLOR_BASE,
} from "@/constants";
import { Guante1 } from "utils/Guante1";
import { Guante2 } from "utils/Guante2";

export default function GlovePreview() {
  const [guantePreview, setGuantePreview] = useState({});
  const [paso, setPaso] = useState(SELECCIONAR_BASE);
  const guantes = [Guante1, Guante2];
  return (
    <>
      <Head>
        <title>Glove Preview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        {paso === SELECCIONAR_BASE && (
          <SeleccionadorModelo
            modelos={guantes}
            setGuantePreview={setGuantePreview}
            setPaso={setPaso}
          />
        )}
        {paso === SELECCIONAR_PALMA && (
          <SeleccionadorPalma
            modelos={guantes}
            setGuantePreview={setGuantePreview}
            setPaso={setPaso}
          />
        )}
        {paso === SELECCIONAR_LATIGO && (
          <SeleccionadorLatigo
            modelos={guantes}
            setGuantePreview={setGuantePreview}
            setPaso={setPaso}
          />
        )}
        {paso === SELECCIONAR_COLOR_BASE && (
          <Personalizador modelo={guantePreview} setPaso={setPaso} />
        )}
      </main>
    </>
  );
}
