import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Glove Preview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="hero min-h-screen bg-base-200">
        <div className="hero-content text-center">
          <div className="max-w-md">
            <h1 className="text-5xl font-bold mb-5">Personalizador v.0.1</h1>
            <p className="text-xl py-6 mb-10">
              Este es una prueba de concepto para el personalizador de guantes.
              <br></br>
              <br></br>Por el momento solo se considera diseño para computadora.
            </p>

            <Link href="/glovepreview">
              <button className="btn btn-accent">Ir al personalizador</button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
